from graphviz import Digraph

dot = Digraph(comment='Secure Image Sharing Chat System')

# Entry point
dot.node('Start', 'START')
dot.node('Visit', 'User Visits Homepage')
dot.node('HasAcc', 'Has Account?')
dot.node('Signup', 'Fill Signup Form\n(Username, Password, Role)')
dot.node('SubscriberCheck', 'Is Role = Subscriber?')
dot.node('GenKey', 'Generate RSA Key\n(Save PEM file)')
dot.node('SaveUser', 'Save User to DB')
dot.node('LoginPage', 'Redirect to Login Page')
dot.node('Login', 'Login with Username & Password')
dot.node('ValidCred', 'Are Credentials Valid?')
dot.node('Error', 'Login Failed\nShow Error Message')
dot.node('Dashboard', 'Redirect to Dashboard')
dot.node('Admin', 'Admin Dashboard')
dot.node('Upload', 'Upload Image\n[Encrypt? Checkbox]')
dot.node('StoreFile', 'Store File Info in DB & uploads/')
dot.node('Subscriber', 'Subscriber Dashboard')
dot.node('ViewBlur', 'View Encrypted Image (Blurred)')
dot.node('UploadKey', 'Upload PEM Key')
dot.node('ValidKey', 'Is Key Valid?')
dot.node('ShowImage', 'Unlock Image')
dot.node('InvalidKey', 'Show Key Error')
dot.node('User', 'Regular User Dashboard')
dot.node('PublicOnly', 'Can View Public Images Only')
dot.node('PromptSub', '"Subscribe to view encrypted files"')
dot.node('Logout', 'Logout → Clear Session')
dot.node('End', 'END')

# Flow connections
dot.edges([('Start', 'Visit'),
           ('Visit', 'HasAcc')])
dot.edge('HasAcc', 'Signup', label='No')
dot.edge('Signup', 'SubscriberCheck')
dot.edge('SubscriberCheck', 'GenKey', label='Yes')
dot.edge('SubscriberCheck', 'SaveUser', label='No')
dot.edge('GenKey', 'SaveUser')
dot.edge('SaveUser', 'LoginPage')
dot.edge('HasAcc', 'Login', label='Yes')
dot.edge('Login', 'ValidCred')
dot.edge('ValidCred', 'Error', label='No')
dot.edge('ValidCred', 'Dashboard', label='Yes')
dot.edge('Dashboard', 'Admin', label='Role = Admin')
dot.edge('Admin', 'Upload')
dot.edge('Upload', 'StoreFile')
dot.edge('Dashboard', 'Subscriber', label='Role = Subscriber')
dot.edge('Subscriber', 'ViewBlur')
dot.edge('ViewBlur', 'UploadKey')
dot.edge('UploadKey', 'ValidKey')
dot.edge('ValidKey', 'ShowImage', label='Yes')
dot.edge('ValidKey', 'InvalidKey', label='No')
dot.edge('Dashboard', 'User', label='Role = Regular User')
dot.edge('User', 'PublicOnly')
dot.edge('User', 'PromptSub')
dot.edge('Dashboard', 'Logout')
dot.edge('Logout', 'End')

# Output the flowchart to file
dot.render('secure_image_flowchart', format='png', cleanup=False)
print("Flowchart saved as secure_image_flowchart.png")
